version: '2'
services:
  postgres:
    build:
      context: docker
    environment:
      - POSTGRES_DB=chronicles_django_perf
      - POSTGRES_USER=testuser
      - POSTGRES_PASSWORD=password
    ports:
      - "5432:5432"
